config/routes.rb
Rails.application.routes.draw do
  get 'urls/shorten'
  resources :urls, only: [:create, :show,]
  get '/redirecturl/:id', to: 'urls#redirecturl'
  
  # resources :urls do
  #   member do
  #     get 'redirecturl'
  #   end
  # end
  # get 'urls/shorten'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  extend FriendlyId
  friendly_id :newurl, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def gen_hash(url)
    return Digest::MD5.hexdigest(url).scan(/[a-zA-Z]/).join("")[0..8]
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def shorten
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    @url['newurl'] =  gen_hash(@url['oldurl'])
    @url.save!
    redirect_to action: 'redirecturl', id: @url.id
  end

  def show
    @url = Url.friendly.find(params[:id])
    redirect_to "http://www.#{@url.oldurl}"
  end
  
  def redirecturl
    @url = Url.find(params[:id])
  end

  private
    def url_params
      params.require(:url).permit(:oldurl)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urlshort</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/redirecturl.html.erb
Here's your shortened link!
<%= link_to "localhost:3000/urls/#{@url.newurl}", url_path(@url.id) %>

app/views/urls/shorten.html.erb
www.<%= form_for @url, url: {action: "create"}, html: {class: "url_shorten"} do |f| %>
  <%= f.text_field :oldurl %>
  <%= f.submit "Create" %>
<% end %>